name: CI Build

on:
  push:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: make
      run: make scanner

